### PR TITLE
windows compat. fixes

### PR DESCRIPTION
**Pull request by Sivecano**

### CODE REVIEW

**Comment by KalokaK** [comment]
Those are windows compat?

**Comment by Sivecano** [comment]
> 
> 
> Those are windows compat?

yes endian.h is not a standard library, chess::castle had an issue where it sometimes wouldn't return anything, for typeid to work in eventsystem.cxx you needed to include typinfo and in chesssprite handler you needed to do some conversions od paths into string

**Comment by KalokaK** [comment]
hmm. curious... the endian thing was a meme anyway, oof thanks about that castle thing, did not see, uhhhhhh... typeid... thas weird as hell. maybe I delted it while cleaning up? this codebase is such a mese. there are bunch of rendundant classes and functions and what have you not.... its horrid.

**Comment by KalokaK** [comment]
yes I guess will merge, or maybe just windows branch...

**Comment by Sivecano** [comment]
> 
> 
> hmm. curious... the endian thing was a meme anyway, oof thanks about that castle thing, did not see, uhhhhhh... typeid... thas weird as hell. maybe I delted it while cleaning up? this codebase is such a mese. there are bunch of rendundant classes and functions and what have you not.... its horrid.

for endianness on windows the only good solution i have previously found is intrin.h

**Comment by KalokaK** [comment]
thanks for the help dude.

**Comment by KalokaK** [comment]
tf is that header name srysly thas so dumb. what it do?

**Comment by Sivecano** [comment]
> 
> 
> tf is that header name srysly thas so dumb. what it do?

contains some stuff **intrinsic** to the compiler.... kinda cancerous

**Comment by KalokaK** [comment]
ah yes. I guess not such a misnomer then im dum. Nah I think the meme is not worth it.... like at all...

**Pull request merged**
